# fly.toml app configuration file generated for sp-bird-sighting on 2023-08-10T23:24:14-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "sp-bird-sighting"
primary_region = "lax"

[build]

[http_service]
  internal_port = 3030
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
